# Generated by Django 3.0.8 on 2020-08-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='buy_online',
            field=models.CharField(help_text='Enter a link to buy this book online', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=5, null=True, verbose_name='Price(INR)'),
        ),
    ]
