# Generated by Django 3.0.8 on 2020-08-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200806_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(max_length=20, null=True, verbose_name='Edition'),
        ),
        migrations.AlterField(
            model_name='book',
            name='buy_online',
            field=models.CharField(help_text='Enter a link to buy this book online', max_length=200, null=True, verbose_name='Buy Online'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Price(INR)'),
        ),
    ]
