# Generated by Django 3.0.8 on 2020-08-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200811_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
